targets = [
    "aarch64-apple-darwin",
    "aarch64-pc-windows-msvc",
    "aarch64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
    "x86_64-unknown-linux-gnu",
]

accepted = [
    "Apache-2.0",
    "MIT",
    "BSD-3-Clause",
    "MPL-2.0",
    "GPL-3.0",
    "Unicode-DFS-2016",
]

ignore-build-dependencies = true
ignore-dev-dependencies = true
filter-noassertion = true
private = { ignore = true }

[half.clarify]
license = "MIT OR Apache-2.0"

[[half.clarify.files]]
path = "LICENSES/MIT.txt"
license = "MIT"
checksum = "b85dcd3e453d05982552c52b5fc9e0bdd6d23c6f8e844b984a88af32570b0cc0"

[[half.clarify.files]]
path = "LICENSES/Apache-2.0.txt"
license = "Apache-2.0"
checksum = "074e6e32c86a4c0ef8b3ed25b721ca23aca83df277cd88106ef7177c354615ff"
